version: '3'
services:

  # postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - 5432:5432

  db-timeseries:
    container_name: influxdb
    image: influxdb:1.5.2
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DB: influxdb
    ports:
      - 8086:8086

  grafana:
    container_name: grafana_local
    image: grafana/grafana
    ports:
      - 3000:3000
